import 'package:flutter/material.dart';

final appTheme = ThemeData(
  canvasColor: Colors.black,
  cardColor: Colors.black,
  //colorScheme: ColorScheme(background: Colors.black),
  colorSchemeSeed: Colors.black,
  dialogBackgroundColor: Colors.black,
  disabledColor: Colors.black,
  //  Color? canvasColor,
  //   Color? cardColor,
  //   ColorScheme? colorScheme,
  //   Color? colorSchemeSeed,
  //   Color? dialogBackgroundColor,
  //   Color? disabledColor,
  //   Color? dividerColor,
  //   Color? focusColor,
  //   Color? highlightColor,
  //   Color? hintColor,
  //   Color? hoverColor,
  //   Color? indicatorColor,
  //   Color? primaryColor,
  //   Color? primaryColorDark,
  //   Color? primaryColorLight,
  //   MaterialColor? primarySwatch,
  //   Color? scaffoldBackgroundColor,
  //   Color? secondaryHeaderColor,
  //   Color? shadowColor,
  //   Color? splashColor,
  //   Color? unselectedWidgetColor,
  appBarTheme: const AppBarTheme(
    backgroundColor: Colors.white,
    elevation: 0,
  ),
  navigationBarTheme: const NavigationBarThemeData(
    backgroundColor: Colors.white,
    elevation: 0,
    shadowColor: Colors.white,
    surfaceTintColor: Colors.white,
    indicatorColor: Colors.white,
  ),
  textTheme: TextTheme(
    bodyMedium: const TextStyle(
      color: Colors.white,
      fontWeight: FontWeight.w500,
      fontSize: 20,
    ),
    labelSmall: TextStyle(
      color: Colors.white.withOpacity(0.6),
      fontWeight: FontWeight.w700,
      fontSize: 14,
    ),
  ),
  scaffoldBackgroundColor: Colors.white,
  // colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
  // useMaterial3: true,
);
